name: bybit-snapshot

on:
  schedule:
    # KST 00·06·12·18 (UTC 15,21,03,09)
    - cron: "0 15,21,3,9 * * *"
  workflow_dispatch: {}

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Ensure folders
        run: mkdir -p data scripts

      - name: Run snapshot (use script in repo)
        run: |
          python scripts/bybit_snapshot.py

      - name: Show snapshot.json (for debug)
        run: |
          test -f data/snapshot.json && head -n 50 data/snapshot.json || echo "snapshot.json not found"

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/snapshot.json
          git commit -m "auto: update snapshot $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "no changes"
          git push
